### ISSUE TITLE
When i try to refresh the motd, this ERROR appears on my console.

### ISSUE THREAD

**Issue by albus12138** [aadnk/ProtocolLib#106]
[14:36:56 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: source cannot be null!
        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
        at com.comphenix.protocol.reflect.FuzzyReflection.getFields(FuzzyReflection.java:582)
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldListByType(FuzzyReflection.java:415)
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:394)
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:595)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:534)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131)
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
        at java.lang.Thread.run(Thread.java:745)
  Dump:
  Parameters:
    io.netty.buffer.UnpooledHeapByteBuf@594f50d[
      alloc=io.netty.buffer.UnpooledByteBufAllocator@4832f2f0
      array={1,0,0,0,0,1,57,-65,17}
      tmpNioBuf=<null>
      refCnt=1
      readerIndex=9
      writerIndex=9
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
      swappedBuf=<null>
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3de69078[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@29d5ddd4
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5eaee4e6
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@200241e4
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@296e70cc
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2ed23348
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7727ba0
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@1bd9885c
        reporter=com.comphenix.protocol.ProtocolLib$1@354d07cb
        server=CraftServer{serverName=Cauldron,serverVersion=1.7.10-1614.56,minecraftVersion=1.7.10}
        library=ProtocolLib v4.0.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5088cf7a
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1f5a7074
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4338dcae
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.7.10)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@33f8d14e
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@46db2c2a[
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@a4e3d55
      player=com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$c69ad3dc@f965d1e
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@7a119f03
      originalChannel=[id: 0xe4cb49b4, /125.37.81.31:56569 => /10.105.7.53:25565]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=private io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@7a119f03, previous=[id: 0xe4cb49b4, /125.37.81.31:56569 => /10.105.7.53:25565], current=com.comphenix.protocol.injector.netty.ChannelInjector$5@1eeb6b61, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      scheduleProcessPackets=com.comphenix.protocol.injector.netty.ChannelInjector$1@4ef8a611
      vanillaDecoder=net.minecraft.util.MessageDeserializer@535445cb
      vanillaEncoder=net.minecraft.util.MessageSerializer@5fd6b748
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@1f5a7074
      processor=com.comphenix.protocol.injector.NetworkProcessor@b92b039
      injected=true
      closed=false
      cumulation=UnpooledHeapByteBuf(ridx: 9, widx: 9, cap: 9)
      singleDecode=false
      decodeWasNull=false
      added=true
    ]
  Version:
    ProtocolLib v4.0.1
  Java Version:
    1.8.0_71
  Server:
    1.7.10-1614.56 (MC: 1.7.10)

**Comment by dmulloy2** [comment]
1.7 is long obsolete, but you should use build 232: http://ci.dmulloy2.net/job/ProtocolLib/232/
