### ISSUE TITLE
Bed packet errors

### ISSUE THREAD

**Issue by TerZer** [aadnk/ProtocolLib#134]
Trying this code:
````java    private void playSleepAnimation(Player asleep) {
        final PacketContainer bedPacket = manager.createPacket(PacketType.Play.Server.BED, false);
        final Location loc = asleep.getLocation();
        BlockPosition blockPos = new BlockPosition(loc.getBlock().getX(), loc.getBlock().getY(), loc.getBlock().getZ());
       
        // [url]http://wiki.vg/Protocol#Use_Bed[/url]
        bedPacket.getEntityModifier(asleep.getWorld()).
            write(0, asleep);
        bedPacket.getBlockPositionModifier().
            write(1, blockPos);
        broadcastNearby(asleep, bedPacket);
    }
````

But it's not working and trows error:
`[11:03:37 ERROR]: Could not pass event PlayerInteractEvent to PrisonSirdis v0.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:913) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-fbb47e8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:352) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:328) ~[?:?]
        at lt.TerZer.PrisonSirdis.Listeners.PlayerListener.playSleepAnimation(PlayerListener.java:92) ~[?:?]
        at lt.TerZer.PrisonSirdis.Listeners.PlayerListener.onRightClick(PlayerListener.java:72) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3fb9445-fbb47e8]
        ... 17 more]`

**Comment by MiniDigger** [comment]
change the index for the block position modifier to 0 when writing, there is only one block position in that packet so you can't write to index 1 (which would be the second block position in the packet)

**Comment by TerZer** [comment]
I changed, no error now, but player sleeping not shown how to fix that?
code:
`    private void playSleepAnimation(Player asleep) {
        final PacketContainer bedPacket = manager.createPacket(PacketType.Play.Server.BED);
        final Location loc = asleep.getLocation();
 
        BlockPosition blockPos = new BlockPosition(loc.getBlock().getX(), loc.getBlock().getY(), loc.getBlock().getZ());
        
        // [url]http://wiki.vg/Protocol#Use_Bed[/url]
        bedPacket.getEntityModifier(asleep.getWorld()).
            write(0, asleep);
        bedPacket.getBlockPositionModifier().write(0, blockPos);
 
        broadcastNearby(asleep, bedPacket);
    }`

**Comment by MiniDigger** [comment]
the client will only render the sleeping player if it thinks that there is a bed at that position. so you need to send a block update first iirc.
