### ISSUE TITLE
ProtocolLib does not support plugin reloaders!

### ISSUE THREAD

**Issue by LowTix** [aadnk/ProtocolLib#168]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [Y ] You're using the latest build for your server version
- [~ ] This isn't an issue caused by another plugin
- [Y ] You've checked for duplicate issues
- [N ] You didn't use `/reload`

Debug paste link:
`[09:22:43] [Server thread/ERROR]: tried to access method com.comphenix.protocol.ProtocolLogger.init(Lorg/bukkit/plugin/Plugin;)V from class com.comphenix.protocol.ProtocolLib initializing ProtocolLib v4.4.0 (Is it up to date?)
java.lang.IllegalAccessError: tried to access method com.comphenix.protocol.ProtocolLogger.init(Lorg/bukkit/plugin/Plugin;)V from class com.comphenix.protocol.ProtocolLib
	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:155) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`
`[09:22:45] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.4.0
[09:22:45] [Server thread/ERROR]: ******************************************************
[09:22:45] [Server thread/ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[09:22:45] [Server thread/ERROR]: *** Please use the built-in reload command!        ***
[09:22:45] [Server thread/ERROR]: ******************************************************
[09:22:45] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.4.0`

Description and relevant errors:
Hello,
I have this error when launching ProtocolLib. I originally had PaperSpigot, then I put Spigot, and then I removed Plugman. Nothing works. I already had this problem but I do not know how I had it adjusted ^^
Thaaaaanks ♥

**Comment by Shocapoite** [comment]
I've got the same problem :/

**Comment by CryLegende** [comment]
Hello,
Same for me, ProtocolLib won't start on one of my server, he say "ProtocolLib does not support plugin reloaders!" but I have start my server normally...

Thank for your help !!

**Comment by ChefMC** [comment]
The same on Paper 1.20.2 with ProtocolLib 5.1.0

```
[20:24:43 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[20:24:43 WARN]: [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
[20:24:44 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib_5.1.0.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib_5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib_5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib_5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib_5.1.0.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib_5.1.0.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib_5.1.0.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@20878d37[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@5dec0751
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@2b364b89
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@36c3c693
      server=CraftServer{serverName=SlimeWorldManager,serverVersion=git-SlimeWorldManager-15432,minecraftVersion=1.20.2}
      file=plugins\ProtocolLib_5.1.0.jar
      description=org.bukkit.plugin.PluginDescriptionFile@17da57c1
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@17da57c1
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\ProtocolLib_5.1.0.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@26f684b8
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.7
  Server:
    git-SlimeWorldManager-15432 (MC: 1.20.2)



...


[20:24:46 INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[20:24:46 ERROR]: ******************************************************
[20:24:46 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[20:24:46 ERROR]: *** Please use the built-in reload command!        ***
[20:24:46 ERROR]: ******************************************************
[20:24:46 INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0
```

**Comment by lbalcita** [comment]
literally same on purpur 1.20.2. Looking for a fix or an explanation as to what can trigger this exactly in other plugins.
