### ISSUE TITLE
[1.8] NPE when player teleported using essentials

### ISSUE THREAD

**Issue by hunter688** [aadnk/ProtocolLib#81]
[14:40:06] [Server thread/INFO]: ovcafr1 issued server command: /tp Rabbitr
[14:40:06] [Server thread/WARN]: com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 0, Size: 0)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:193)
[14:40:06] [Server thread/WARN]: 	at org.kitteh.tag.handler.ProtocolLibHandler$1.onPacketSending(ProtocolLibHandler.java:54)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:368)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:61)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:334)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:302)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:868)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:328)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:426)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.EntityTracker.addEntity(EntityTracker.java:112)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.EntityTracker.addEntity(EntityTracker.java:93)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.EntityTracker.track(EntityTracker.java:27)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.WorldManager.a(WorldManager.java:18)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.World.a(World.java:1060)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.WorldServer.a(WorldServer.java:953)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.World.addEntity(World.java:1053)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.World.addEntity(World.java:981)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerList.moveToWorld(PlayerList.java:561)
[14:40:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.teleport(CraftPlayer.java:475)
[14:40:06] [Server thread/WARN]: 	at com.earth2me.essentials.Teleport.now(Teleport.java:126)
[14:40:06] [Server thread/WARN]: 	at com.earth2me.essentials.Teleport.teleport(Teleport.java:194)
[14:40:06] [Server thread/WARN]: 	at com.earth2me.essentials.Teleport.teleport(Teleport.java:151)
[14:40:06] [Server thread/WARN]: 	at com.earth2me.essentials.commands.Commandtp.run(Commandtp.java:41)
[14:40:06] [Server thread/WARN]: 	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180)
[14:40:06] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527)
[14:40:06] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402)
[14:40:06] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:40:06] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:40:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[14:40:06] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[14:40:06] [Server thread/WARN]: 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
[14:40:06] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[14:40:06] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:722)
[14:40:06] [Server thread/WARN]: com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 0, Size: 0)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:193)
[14:40:06] [Server thread/WARN]: 	at org.kitteh.tag.handler.ProtocolLibHandler$1.onPacketSending(ProtocolLibHandler.java:54)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:368)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:61)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:334)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:302)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110)
[14:40:06] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:868)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:328)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.EntityTracker.a(EntityTracker.java:234)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.EntityPlayer.s_(EntityPlayer.java:259)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1590)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.World.g(World.java:1565)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1412)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:757)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[14:40:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[14:40:06] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:722)

**Comment by aadnk** [comment]
TagAPI is not compatible with Spigot 1.8.
