### ISSUE TITLE
Help weird error.

### ISSUE THREAD

**Issue by Optigonnn** [aadnk/ProtocolLib#82]
[22:48:13 WARN]: FieldAccessException: No field with type java.lang.String exists in class PacketPlayOutNamedEntitySpawn.
[22:48:13 WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197)
[22:48:13 WARN]: 	at org.kitteh.tag.handler.ProtocolLibHandler$1.onPacketSending(ProtocolLibHandler.java:54)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:368)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:61)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:334)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:302)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110)
[22:48:13 WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:868)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:328)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.EntityTracker.a(EntityTracker.java:234)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.EntityPlayer.s_(EntityPlayer.java:259)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1590)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.World.g(World.java:1565)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1412)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:757)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[22:48:13 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[22:48:13 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by dmulloy2** [comment]
TagAPI is completely broken. Remove it.
