### ISSUE TITLE
java.lang.NullPointerException error with cauldron 1.7.10 (build: 1236)

### ISSUE THREAD

**Issue by MineMine** [aadnk/ProtocolLib#83]
[14:41:57] [Server thread/INFO]: [ProtocolLib] Created default configuration.
[14:41:57] [Server thread/ERROR]: null initializing ProtocolLib v3.4.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at com.comphenix.protocol.ProtocolConfig.isDebug(ProtocolConfig.java:253) ~[?:?]
	at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:196) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:325) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:458) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:350) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]

what should i do?

**Comment by dmulloy2** [comment]
We can no longer officially support Cauldron (no source or downloads), but your best bet is to try build 10: http://ci.shadowvolt.com/job/ProtocolLib/10/

**Comment by MineMine** [comment]
thank you for your comment 

I've already tried build #10 but same error appears in the console 

[15:10:29] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v3.6.0-SNAPSHOT
[15:10:29] [Server thread/INFO]: [ProtocolLib] Created default configuration.
[15:10:29] [Server thread/ERROR]: null initializing ProtocolLib v3.6.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at com.comphenix.protocol.ProtocolConfig.isDebug(ProtocolConfig.java:253) ~[?:?]
	at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:193) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:325) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:458) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:350) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]

:(

**Comment by MineMine** [comment]
something wrong with generation configuration file? right?

**Comment by dmulloy2** [comment]
This seems to be a somewhat common issue (https://github.com/dmulloy2/ProtocolLib/issues/10).  The issue is that JavaPlugin#getConfig() is returning null when using Cauldron, but I can't seem to figure out the cause.  It certainly doesn't help that Cauldron was effectively discontinued.
