### ISSUE TITLE
Unable to intercept a read client packet

### ISSUE THREAD

**Issue by SunsetAuditore** [aadnk/ProtocolLib#88]
Trying to use SkinRestores, tyhis error appear in console and chat... Any ideas?

[22:19:20] [Netty IO #0/INFO]: Error Unable to intercept a read client packet. (java.lang.NullPointerException) occured in com.comphenix.protocol.injector.netty.ChannelInjector@1be17ad9.
[22:19:20] [Netty IO #0/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NullPointerException
  	at com.comphenix.protocol.reflect.FuzzyReflection.getFields(FuzzyReflection.java:551)
  	at com.comphenix.protocol.reflect.FuzzyReflection.getFieldListByType(FuzzyReflection.java:382)
  	at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:361)
  	at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:554)
  	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:495)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131)
  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
  	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:240)
  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
  	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447)
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
  	at java.lang.Thread.run(Unknown Source)
  Dump:
  Parameters: 
    io.netty.buffer.UnpooledHeapByteBuf@14fafdba[
      alloc=io.netty.buffer.UnpooledByteBufAllocator@52d8d3a0
      array={3,0}
      tmpNioBuf=<null>
      refCnt=1
      readerIndex=2
      writerIndex=2
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
      swappedBuf=<null>
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3f263574[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@125b11d8
        packetListeners=[PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist{priority=NORMAL, packets=[UNREGISTERED [PLAY, SERVER, 15, legacy: 24], UNREGISTERED [PLAY, SERVER, 14, legacy: 23], UNREGISTERED [PLAY, SERVER, 28, legacy: 40]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.NettyProtocolInjector$5@18f08552
        playerInjection=com.comphenix.protocol.injector.netty.NettyProtocolInjector$4@56c0d748
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@e75e477
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5dea480b
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@401ffa58
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@356103c7
        reporter=com.comphenix.protocol.ProtocolLibrary$1@736cc84b
        server=CraftServer{serverName=Cauldron-MCPC-Plus,serverVersion=KCauldron-1.7.10-2.1403.1.54,minecraftVersion=1.7.10}
        library=ProtocolLib v3.6.3-SNAPSHOT
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7caa54a9
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=1
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.NettyProtocolInjector@6bc7b5ba
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@46bfd9e
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.7.10)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@4dd79256
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@1be17ad9[
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@76bbd2a5
      player=CraftPlayer{name=SunsetAuditore}
      updated=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@1a2aa974
      originalChannel=[id: 0x6d6ebfcb, /127.0.0.1:56133 => /127.0.0.1:25565]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=private io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@1a2aa974, previous=[id: 0x6d6ebfcb, /127.0.0.1:56133 => /127.0.0.1:25565], current=com.comphenix.protocol.injector.netty.ChannelInjector$5@36f6eec2, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      scheduleProcessPackets=com.comphenix.protocol.injector.netty.ChannelInjector$1@db51ebf
      vanillaDecoder=net.minecraft.util.MessageDeserializer@6df594a0
      vanillaEncoder=net.minecraft.util.MessageSerializer@15f0ccc6
      protocolEncoder=com.comphenix.protocol.injector.netty.ChannelInjector$3@7413e66a
      finishHandler=com.comphenix.protocol.injector.netty.ChannelInjector$4@467c74af
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.NettyProtocolInjector@6bc7b5ba
      processor=com.comphenix.protocol.injector.NetworkProcessor@112905dd
      injected=true
      closed=false
      cumulation=UnpooledHeapByteBuf(ridx: 2, widx: 2, cap: 2)
      singleDecode=false
      decodeWasNull=false
      added=true
    ]
  Version:
    ProtocolLib v3.6.3-SNAPSHOT
  Server:
    KCauldron-1.7.10-2.1403.1.54 (MC: 1.7.10)

**Comment by dmulloy2** [comment]
Are you using the legacy jar?

**Comment by SunsetAuditore** [comment]
Which one? I tried the oldest one (9.0) and I was still getting this error, both on console and chat... And the newest one (10.0) has the same result.

**Comment by dmulloy2** [comment]
For 1.7.10, you should try using [Build 10](http://ci.shadowvolt.com/job/ProtocolLib/10/)
