### ISSUE TITLE
onPacketSending no longer up to date?

### ISSUE THREAD

**Issue by eric1299** [aadnk/ProtocolLib#89]
[19:50:57 ERROR]: [NorseLand] Unhandled exception occured in onPacketSending(PacketEvent) for NorseLand
com.comphenix.protocol.reflect.FieldAccessException: No field with type java.lang.String exists in class PacketPlayOutChat.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:217) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:196) ~[ProtocolLib.jar:?]
        at me.eric1299.norseland.core$1.onPacketSending(core.java:117) ~[NorseLand.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:288) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:394) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:62) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$6.handleScheduled(ChannelInjector.java:360) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$6.onMessageScheduled(ChannelInjector.java:328) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79) [ProtocolLib.jar:?]
        at net.minecraft.server.v1_8_R2.NetworkManager.a(NetworkManager.java:192) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.NetworkManager.handle(NetworkManager.java:141) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.PlayerConnection.sendPacket(PlayerConnection.java:878) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:150) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer.sendMessage(CraftPlayer.java:157) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:650) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[19:50:57 ERROR]: Parameters:
  net.minecraft.server.v1_8_R2.PacketPlayOutChat@6257142a[
    a=TextComponent{text='', siblings=[TextComponent{text='Unknown command. Type "/help" for help.', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underli
ned=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickE
vent=null, hoverEvent=null, insertion=null}}
    components=<null>
    b=1
  ]
Using spigot 1.8.3
No other high impact plugins
I was attempting to make an "unknown command" message replacer

**Comment by dmulloy2** [comment]
This isn't an issue with ProtocolLib. String-based messages were largely phased out in 1.8 and were replaced by chat components.

**Comment by eric1299** [comment]
Thanks!
